//
//  AppStorageKeys.swift
//  favorecoAPP
//
//  Created by Codex on 2026/07/09.
//

enum AppStorageKeys {
    static let hasCompletedGenreOnboarding = "hasCompletedGenreOnboarding"
    static let showsHomeAttention = "showsHomeAttention"
    static let showsHomeExperienceGallery = "showsHomeExperienceGallery"
    static let showsHomeInbox = "showsHomeInbox"
    static let showsHomeRecentRecords = "showsHomeRecentRecords"
    static let showsHomeCategories = "showsHomeCategories"
    static let showsHomeStatsSummary = "showsHomeStatsSummary"
    static let showsHomeFavorites = "showsHomeFavorites"
    static let followsSystemTextSize = "followsSystemTextSize"
    static let appTextSize = "appTextSize"
    static let fontStyle = "fontStyle"
    static let fontWeight = "fontWeight"
    static let appearanceMode = "appearanceMode"
    static let themeMode = "themeMode"
    static let unifiedThemeColorHex = "unifiedThemeColorHex"
    static let profileDisplayName = "profileDisplayName"
    static let profileImageData = "profileImageData"
    static let iCloudSyncEnabled = "iCloudSyncEnabled"
    static let iCloudSyncActiveAtLaunch = "iCloudSyncActiveAtLaunch"
    static let iCloudSyncStartupError = "iCloudSyncStartupError"
    static let automaticBackupEnabled = "automaticBackupEnabled"
    static let automaticBackupLastCreatedAt = "automaticBackupLastCreatedAt"
    static let automaticBackupUsesICloudDrive = "automaticBackupUsesICloudDrive"
    static let automaticBackupLastICloudCreatedAt = "automaticBackupLastICloudCreatedAt"
    static let automaticBackupICloudError = "automaticBackupICloudError"
    nonisolated static let purchasedPlanCache = "purchasedPlanCache"
    nonisolated static let debugPlanOverride = "debugPlanOverride"
    static let defaultRecordDateMode = "defaultRecordDateMode"
    static let defaultGenreMode = "defaultGenreMode"
    static let lastUsedCategoryTemplateKey = "lastUsedCategoryTemplateKey"
    static let homeSelectedCategoryTemplateKey = "homeSelectedCategoryTemplateKey"
    static let afterSaveRecordAction = "afterSaveRecordAction"
    static let photoAddStartMode = "photoAddStartMode"
    static let photoCompressionQuality = "photoCompressionQuality"
    static let usesURLImportAssist = "usesURLImportAssist"
    static let usesOCRImportAssist = "usesOCRImportAssist"
    static let usesMapSearchAssist = "usesMapSearchAssist"
    static let usesWeatherAutoFill = "usesWeatherAutoFill"
    static let usesInputSuggestionDictionary = "usesInputSuggestionDictionary"
    static let showsExternalCalendarEvents = "showsExternalCalendarEvents"
    static let automaticallyUpdatesExternalCalendar = "automaticallyUpdatesExternalCalendar"
    static let notificationMasterEnabled = "notificationMasterEnabled"
    static let notificationApplicationStartEnabled = "notificationApplicationStartEnabled"
    static let notificationApplicationDeadlineEnabled = "notificationApplicationDeadlineEnabled"
    static let notificationLotteryResultEnabled = "notificationLotteryResultEnabled"
    static let notificationPaymentDeadlineEnabled = "notificationPaymentDeadlineEnabled"
    static let notificationTicketIssueEnabled = "notificationTicketIssueEnabled"
    static let notificationPerformanceReminderEnabled = "notificationPerformanceReminderEnabled"
    static let notificationMembershipExpiryEnabled = "notificationMembershipExpiryEnabled"
    static let notificationMemoryReminderEnabled = "notificationMemoryReminderEnabled"
    static let notificationMonthlyReportEnabled = "notificationMonthlyReportEnabled"
    static let opensPreviousMonthlyReport = "opensPreviousMonthlyReport"
    static let opensPreviousYearlyReport = "opensPreviousYearlyReport"
}
